baseURL = 'https://osawa-koki.github.io/DB2023/'
languageCode = 'ja-jp'
title = 'データベーススペシャリスト試験対策'
defaultContentLanguage = "ja"
hasCJKLanguage = true

[params]

pages = [
  'インデックス',
  'データベース基礎',
  'foofoo',
]

columns = [
  'インデックス',
  'データベース全般',
  'foofoo',
]
